/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	volumesnapshotv1 "github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeSnapshotLister helps list VolumeSnapshots.
// All objects returned here must be treated as read-only.
type VolumeSnapshotLister interface {
	// List lists all VolumeSnapshots in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*volumesnapshotv1.VolumeSnapshot, err error)
	// VolumeSnapshots returns an object that can list and get VolumeSnapshots.
	VolumeSnapshots(namespace string) VolumeSnapshotNamespaceLister
	VolumeSnapshotListerExpansion
}

// volumeSnapshotLister implements the VolumeSnapshotLister interface.
type volumeSnapshotLister struct {
	listers.ResourceIndexer[*volumesnapshotv1.VolumeSnapshot]
}

// NewVolumeSnapshotLister returns a new VolumeSnapshotLister.
func NewVolumeSnapshotLister(indexer cache.Indexer) VolumeSnapshotLister {
	return &volumeSnapshotLister{listers.New[*volumesnapshotv1.VolumeSnapshot](indexer, volumesnapshotv1.Resource("volumesnapshot"))}
}

// VolumeSnapshots returns an object that can list and get VolumeSnapshots.
func (s *volumeSnapshotLister) VolumeSnapshots(namespace string) VolumeSnapshotNamespaceLister {
	return volumeSnapshotNamespaceLister{listers.NewNamespaced[*volumesnapshotv1.VolumeSnapshot](s.ResourceIndexer, namespace)}
}

// VolumeSnapshotNamespaceLister helps list and get VolumeSnapshots.
// All objects returned here must be treated as read-only.
type VolumeSnapshotNamespaceLister interface {
	// List lists all VolumeSnapshots in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*volumesnapshotv1.VolumeSnapshot, err error)
	// Get retrieves the VolumeSnapshot from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*volumesnapshotv1.VolumeSnapshot, error)
	VolumeSnapshotNamespaceListerExpansion
}

// volumeSnapshotNamespaceLister implements the VolumeSnapshotNamespaceLister
// interface.
type volumeSnapshotNamespaceLister struct {
	listers.ResourceIndexer[*volumesnapshotv1.VolumeSnapshot]
}
