
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: volumesnapshotclasses.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io
  names:
    kind: VolumeSnapshotClass
    plural: volumesnapshotclasses
  scope: ""
  validation:
    openAPIV3Schema:
      description: VolumeSnapshotClass describes the parameters for a class of storage
        snapshotter for which VolumeSnapshot can be dynamically taken for a given
        PersistentVolumeClaim VolumeSnapshotClasses are non-namespaced. The name of
        a VolumeSnapshotClass object is significant, it serves as the unique identifier
        for a user to request a snapshot to be created using the specific VolumeSnapshotClass
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        deletionPolicy:
          description: DeletionPolicy defines whether a VolumeSnapshotContent and
            its associated physical snapshot on underlying storage system should be
            deleted or not when released from its corresponding VolumeSnapshot. If
            not specified, the default will be VolumeSnapshotContentRetain for static
            binding, and VolumeSnapshotContentDelete for dynamic snapshot creation.
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
          type: object
        parameters:
          additionalProperties:
            type: string
          description: Parameters holds parameters for underlying storage system.
            These values are opaque to Kubernetes.
          type: object
        snapshotter:
          description: Snapshotter is the name of the driver expected to handle VolumeSnapshot
            requests of this VolumeSnapshotClass.
          type: string
      required:
      - snapshotter
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
