
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: volumesnapshotclasses.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io
  names:
    kind: VolumeSnapshotClass
    plural: volumesnapshotclasses
  scope: ""
  version: v1beta1
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: VolumeSnapshotClass describes the parameters used by storage
          system when provisioning VolumeSnapshots from PVCs. The name of a VolumeSnapshotClass
          object is significant, and is how users can request a particular class.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          deletionPolicy:
            description: 'Optional: what happens to a snapshot content when released
              from its snapshot. The default policy is Delete if not specified.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
            type: object
          parameters:
            additionalProperties:
              type: string
            description: Parameters holds parameters for the snapshotter. These values
              are opaque to the system and are passed directly to the snapshotter.
            type: object
          snapshotter:
            description: Snapshotter is the driver expected to handle this VolumeSnapshotClass.
            type: string
        required:
        - snapshotter
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
