/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta2 "github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VolumeGroupSnapshotClassLister helps list VolumeGroupSnapshotClasses.
// All objects returned here must be treated as read-only.
type VolumeGroupSnapshotClassLister interface {
	// List lists all VolumeGroupSnapshotClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta2.VolumeGroupSnapshotClass, err error)
	// Get retrieves the VolumeGroupSnapshotClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta2.VolumeGroupSnapshotClass, error)
	VolumeGroupSnapshotClassListerExpansion
}

// volumeGroupSnapshotClassLister implements the VolumeGroupSnapshotClassLister interface.
type volumeGroupSnapshotClassLister struct {
	indexer cache.Indexer
}

// NewVolumeGroupSnapshotClassLister returns a new VolumeGroupSnapshotClassLister.
func NewVolumeGroupSnapshotClassLister(indexer cache.Indexer) VolumeGroupSnapshotClassLister {
	return &volumeGroupSnapshotClassLister{indexer: indexer}
}

// List lists all VolumeGroupSnapshotClasses in the indexer.
func (s *volumeGroupSnapshotClassLister) List(selector labels.Selector) (ret []*v1beta2.VolumeGroupSnapshotClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta2.VolumeGroupSnapshotClass))
	})
	return ret, err
}

// Get retrieves the VolumeGroupSnapshotClass from the index for a given name.
func (s *volumeGroupSnapshotClassLister) Get(name string) (*v1beta2.VolumeGroupSnapshotClass, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta2.Resource("volumegroupsnapshotclass"), name)
	}
	return obj.(*v1beta2.VolumeGroupSnapshotClass), nil
}
