kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.snapshotController.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
  minReadySeconds: 35
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller
      containers:
        - name: snapshot-controller
          image: {{ .Values.snapshotController.snapshotController.image.repository }}:{{ .Values.snapshotController.snapshotController.image.tag }}
          args:
            - --v=5
            - --leader-election=true
          imagePullPolicy: {{ .Values.snapshotController.snapshotController.image.pullPolicy }}
